name: PHPStan

on:
    push:
        paths:
            - '**.php'
            - 'phpstan.neon.dist'

jobs:
    phpstan:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v5

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

            - name: Run PHPStan
              timeout-minutes: 2
              run: ./vendor/bin/phpstan analyse --error-format=github
